### ISSUE TITLE
Cart includes

### ISSUE THREAD

**Issue by ChillyWillyGuru** [ijacquez/libyaul#34] opened 2016-05-20 22:56 UTC
Looking at the current yaul.h, shouldn't the section for CS0 be more like this?

`/* CS0 */`
`#if HAVE_DEV_CART == 1`
`#include <scu/bus/a/cs0/usb-cartridge/usb-cartridge.h>`
`#elif HAVE_DEV_CART == 2`
`#include <scu/bus/a/cs0/arp/arp.h>`
`#else`
`#include <scu/bus/a/cs0/dram-cartridge/dram-cartridge.h>`
`#endif`

**Comment by ijacquez** [comment] 2016-05-20 23:50
Yeah, it was exactly like that.

Now, I'm not 100% sure if I should do that. Instead, provide "stubs" for features that are compiled out. Projects do have `HAVE_DEV_CARTRIDGE` define, and they can include/exclude snippets of code depending on the value they have set. But it becomes rather annoying when you have these functions littered everywhere.

So I do plan to have these files included, but depending on the value of `HAVE_DEV_CARTRIDGE`, link stubs. I'm looking into weak C symbols.

Do you have a better idea?

**Comment by ChillyWillyGuru** [comment] 2016-05-21 18:09
Maybe have the post make file check if `HAVE_DEV_CARTRIDGE` has been defined, and if not, define it as 0. Then projects will only define it when they actually use.

Another idea is to make functions that check if you have a USB cart, or ARP cart, or a mem cart. Have all of them defined in the library, but functions that use them would return an error if the hardware wasn't available. This is probably the cleanest way, but more work on your end.

So projects wouldn't have a define about the hardware, they'd call a function like `hasUsbCart()` or `hasArpCart()` or `hasMemCart(minSize)`. If true is returned, they know they can call functions associated with said hardware. If false, they can show an error message if required, or do something else if not required.

**Comment by ijacquez** [comment] 2016-05-23 21:37
That's a good idea. I do agree that it's more work on my end. I think I'll take the easiest approach, which is to simply do what you suggested. The problem is detecting the type of cart, not necessarily if there a cart present. What also helps is that a project that doesn't need any of this can strip it out completely.

Fixing soon.

**Comment by ChillyWillyGuru** [comment] 2016-05-23 23:47
I've got the USB dev cart, an ARP+ 4in1, and the small official mem cart for testing. I'd have to burn a CD for testing the ARP/mem cart, but I do have a mod chip, so that's not a problem.

**Comment by ijacquez** [comment] 2016-05-24 00:02
For sure, there is an "official" way to detect if RAM carts or if I recall, backup carts are installed.

This feature is only for when your program simply won't use any of the development features of the AR or USB cart. Which in this case, it would make sense to exclude it from the library.

However, if you have an AR cart and wanting to use it as a RAM cart, attempting to detect that a DRAM cartridge is present is a totally different matter. To be more clear, `arp_*()` namespace pertains to communication features in the ARP, but `dram_cartridge_*()` are for either official RAM cart or the ARP cart, even if `OPTION_DEV_CARTRIDGE=0`.

Also, for VFS, I do plan on having all the mounts be done at build time, so this would be troublesome.

I do also have a way to detect if an AR cart is inserted, but I feel uneasy about it. I don't believe I would catch all cases. Same for the USB cart. The firmware was never really standardized.

If you think I missed anything, let me know. I can certainly add this. I'm working on adding documentation, so I could always "warn" users.

**Comment by ChillyWillyGuru** [comment] 2016-05-24 00:45
http://koti.kapsi.fi/~antime/sega/usbcart/usbcart.html

That's the only usb dev cart I'm aware of. Mine was part of a batch not made by the guy above, but using his gerber files.

The AR would be more an issue in my estimation - I know there have been not only a bunch of different revs, but lots of knock-offs as well. For example, mine SHOULD have the parallel port, but doesn't. That's partly why I got the usb dev cart when I had the chance. I'd suggest detecting the ram, and maybe the most common form of dev interface for AR carts and call it good.

**Comment by ijacquez** [comment] 2016-05-25 20:23
I agree. Good news is that detecting the RAM cart is well documented and [complete](https://github.com/ijacquez/libyaul/tree/master/libyaul/scu/bus/a/cs0/dram-cartridge).

If you would like to help out with finding a decent way of detecting the AR and USB cartridges, I can merge your work in :) [Here](https://github.com/ijacquez/libyaul/blob/master/libyaul/scu/bus/a/cs0/arp/arp_version.c) is what I have.

**Comment by ChillyWillyGuru** [comment] 2016-05-25 21:04
Sure, I'll update and do some testing.

**Comment by ChillyWillyGuru** [comment] 2016-05-25 23:29
Quick update. My ARP shows as NULL on the ar-comm test. I noticed that the version just fetches a string at a set location in the AR boot rom. Instead of a fixed location, how about looking for the version over a range of locations. My AR shows "ACTION REPLAY (PLUS) Version 2.02" in the title. If that's similar to the normal version you fetch at that location, maybe use the common word(s) between them in a memcmp to find the version if possible. As far as I can tell, the comm hardware has never changed location. Anywho, the dram test says the ARP has 32Mbit of dram that tests fine. The dram test also says my official Sega 8Mbit card has 8Mbit that tests fine. So I think the dram code is working just peachy. I'll look into the USB cart tonight.

**Comment by ChillyWillyGuru** [comment] 2016-05-26 01:04
Okay, let's start with a little hardware info...

CS0 is not 2240 0000 like in your include. That's a subset of CS0 where DRAM memory should start to be compatible with the DRAM interface in the SCU. CS0 is 2200 0000 and goes to 23FF FFFF. Data carts start at 2200 0000 and are covered by tech bulletin 46. They have a System ID header that starts at 2200 0000 and are 256 bytes long. Although it doesn't say in the bulletin, that's also the same format for boot carts, which is what AR and the USB Dev cart are. The main differences are that the hardware id at offset 0 is "SEGA SEGASATURN " instead of "SEGASATURN DATA ", and the system id area is followed by security codes, followed by the boot code.

The USB Dev cart uses a manufacturer's id (offset $10) of "ANDERS MONTONEN " and a product id (offset $20) of "ANTIME-001". The version is at offset $2A, and is "V1.003" for the last version of the firmware the original dev made. None of these strings are null-terminated.

I suggest changing the CS0 macro in the includes, and then changing the DRAM macro to include the dram offset from CS0 like proper. Make a new include for data carts that uses offsets from the proper CS0 for macros for the different system id fields. Then you can use the data cart macros to look for actual data carts, and to fetch info on boot carts.

**Comment by ijacquez** [comment] 2016-05-26 01:49
Thanks for looking into this. If you have the time, it would be great to have the change merged in. Otherwise, I'll fix that as well.

[Here](https://segaxtreme.net/threads/detecting-usb-flash-cart-and-ar-gameshark-carts.24061/) is a question I asked a while back. I never looked into it because there isn't a truly reliable way of detecting the USB dev cart. Regardless, it would be good have.

**Comment by ChillyWillyGuru** [comment] 2016-05-26 01:57
One person there wrote this
`You can read the cartridge header, but I know there's one CD emulation cartridge that just copied the header without changes.`

I haven't actually written code for the cart stuff, but I could if you want. I think a simple example that reads and displays the system id area for a data/boot cart would be an excellent addition. That would then help in determining a better way to detect AR or USB carts. It may not be perfect, but I don't think perfection is needed here. A CD emulation cart, for example, is really not going to be running ARP comm code, it'll be used for games/homebrew.

**Comment by ijacquez** [comment] 2016-05-26 04:02
Okay, that's the first round of fixes.

**Comment by ChillyWillyGuru** [comment] 2016-05-26 06:07
Just a note if you're working on the cart stuff - the system id block is slightly different between the data cart and boot cart. I made these in the code I'm working on. Each index in the table has the start offset in the rom, the length, and the name of the field. The difference mainly comes after the title.

http://pastebin.com/mdgn7hEh

**Comment by ChillyWillyGuru** [comment] 2016-05-26 06:14
Actually, I'm getting ready to head to bed. Here's an arc of the cart support code I've done to this point. Haven't started on a test app using it yet... I'll work on that tomorrow. Don't know if it's useful to you, but it's kinda how I see cart support going.

http://www.mediafire.com/download/7ev7b9e3r2qnzyy/cart.zip

**Comment by ijacquez** [comment] 2016-05-26 06:32
Yeah, this is great. I'll add this.

**Comment by ChillyWillyGuru** [comment] 2016-05-26 17:06
Looks good. My design was a little over-engineered. :)  Nice and simple does the trick.

**Closed** 2017-09-18 00:36 UTC
Labels: bug, question
